/* crafting-data.js — Crafting materials with verified community farm locations
   Sources: wiki.guildwars.com farming guides, PvX Wiki, GW Legacy (all GNU FDL / community) */
var CRAFTING_MATERIALS = {
  common: [
    { name:'Bone', front:{ use:'Armor crafting, weapon crafting, Scrolls of Resurrection' }, back:{ areas:'Cathedral of Flames (EotN dungeon) — HM yields massive bone drops from undead throughout', drops:'Skeletons, Grasping Ghouls, Restless Dead (CoF has the highest density)', salvageItems:'Bone Staff, Grim Cesta, Jawbone, Ribcage, Skull, Skeletal Limb, Kappa Shell', kit:'Any Salvage Kit' }},
    { name:'Bolt of Cloth', front:{ use:'Light armor crafting, Essences of Celerity' }, back:{ areas:'Vaettir farm (Jaga Moraine HM) — salvage drops. Also any humanoid-heavy zone in NM', drops:'Salvaged primarily, not dropped. Vaettir loot + Kaineng City humanoids', salvageItems:'Any caster salvage armor (robes, outfits, garments), Shaman/Sage/Healer/Ritualist gear', kit:'Any Salvage Kit' }},
    { name:'Chitin Fragment', front:{ use:'Medium armor crafting' }, back:{ areas:'Undercity (Factions) — devourers. Istan/Fahranur (Nightfall) — skree/insects', drops:'Devourers (best single source), Skree Harpies, Giant Spiders, Scarabs', salvageItems:'Baked Husk, Carapace, Spider Leg, Mandible (not jawbones)', kit:'Any Salvage Kit' }},
    { name:'Feather', front:{ use:'Essences of Celerity (high demand)' }, back:{ areas:'Jaya Bluffs (Factions, NM) — fastest farm, 20 Sensali Tengu groups. North Kryta Province (Prophecies) — Caromi Tengu. HM doubles feather drops (~20/run vs ~9 NM)', drops:'Sensali Tengu (Jaya Bluffs), Caromi Tengu (N. Kryta Province)', salvageItems:'Tengu Scalp, Caromi Scalp, Sensali Scalp, Avicara Scalp (Shiverpeaks)', kit:'Any Salvage Kit' }},
    { name:'Granite Slab', front:{ use:'Heavy armor, weapon crafting' }, back:{ areas:'Old Ascalon outside Sardelac Sanitarium (HM, Terra Tank build). Also Morostav Trail VQ run (Echovald)', drops:'Hulking Stone Elementals (best direct drop), Stone Summit dwarves, Gargoyles', salvageItems:'Scorched Lodestone, Rusty Axe, Marble items, some hammers (Jade Maul, Runic Maul, Spiked Club)', kit:'Any Salvage Kit' }},
    { name:'Iron Ingot', front:{ use:'Heavy armor, melee weapons, Deldrimor Steel ingredient' }, back:{ areas:'Vaettir farm (Jaga Moraine HM) — salvage loot into iron. Best bulk source in the game. Also any weapon-heavy drop area', drops:'Iron Ingots do NOT drop from creatures directly — salvage only', salvageItems:'Any metal weapon (swords, axes, daggers, rods, canes, wands). Vaettir farm gold drops salvage into iron efficiently', kit:'Any Salvage Kit (use basic kit for maximum material yield)' }},
    { name:'Pile of Glittering Dust', front:{ use:'Essences of Celerity, Armor of Salvation (high demand)' }, back:{ areas:'Vaettir farm (Jaga Moraine HM) — Glacial Stones salvage into dust. Also Cursed Lands (Prophecies) — Fog Nightmares', drops:'Fog Nightmares (Cursed Lands), Phantoms. Glacial Stones from Vaettirs salvage into dust', salvageItems:'Glacial Stone (from Vaettirs), Jeweled Chalice, Spider Web, Mursaat Token, Jade items, Demonic items, Celestial items', kit:'Any Salvage Kit' }},
    { name:'Plant Fiber', front:{ use:'Medium armor, nature rituals' }, back:{ areas:'The Black Curtain (Prophecies) — plant creatures, dedicated Rt/Me farm builds exist. Holdings of Chokhin (Nightfall) — full loop of plant enemies', drops:'Grasping Roots, Guardian Moss, Dragon Mosses, hostile plants', salvageItems:'Seeds, Grawl Necklaces (primary salvage source)', kit:'Any Salvage Kit' }},
    { name:'Scale', front:{ use:'Medium armor crafting' }, back:{ areas:'North Kryta Province (skale beaches, NM). Istan coast (skale). Any area with dense skale spawns', drops:'Skales (all types — Bog Skale, River Skale, etc.), Naga (occasionally)', salvageItems:'Skale Fin, Naga Pelt, various hides from scaled creatures', kit:'Any Salvage Kit' }},
    { name:'Tanned Hide Square', front:{ use:'Medium armor crafting' }, back:{ areas:'Any beast-heavy zone — Old Ascalon (devourers/beasts NM), Kryta (warthogs)', drops:'Salvaged primarily — not commonly a direct drop', salvageItems:'Most Ranger/Scout salvage items — hides, tunics, vests. Also Half-Digested Masses and Half-Eaten Blobs', kit:'Any Salvage Kit' }},
    { name:'Wood Plank', front:{ use:'Bow, staff, shield crafting' }, back:{ areas:'Echovald Forest VQ runs — lots of staff/bow drops. Any area dropping wooden weapons', drops:'Wood Planks do NOT commonly drop directly — salvage only', salvageItems:'Any bow, staff, wooden shield. Also Charr Carvings, Divine Symbols', kit:'Any Salvage Kit' }},
  ],
  rare: [
    { name:'Glob of Ectoplasm', front:{ use:'Primary trade currency. Obsidian armor (15/piece).' }, back:{ areas:'The Underworld (solo farms: Aatxe Valley, Chaos Planes). Fissure of Woe Shadow Army areas. Solo UW possible with A/Me Shadow Form or 55hp Monk builds', drops:'Aatxes (most reliable ~1 per 3-4 kills), Smite Crawlers, Charged Blackness, Skeletons of Dhuum', salvageItems:'Very rare from any gold item dropped in UW/FoW with Superior Salvage Kit — not a reliable source', kit:'N/A — creature drops (Superior Salvage Kit for slim chance from gold items)' }},
    { name:'Obsidian Shard', front:{ use:'Obsidian armor (15/piece, 75 total). Always in demand.' }, back:{ areas:'Fissure of Woe — quest reward chests. Cannot be reliably farmed solo; requires FoW quest completion', drops:'FoW quest reward chests (1-3 per quest completion)', salvageItems:'Cannot be salvaged', kit:'N/A — quest chest rewards only' }},
    { name:'Diamond', front:{ use:'Vabbian elite armor (6 per piece)' }, back:{ areas:'Domain of Anguish (all 4 zones). Gate of Pain / Nightfallen Jahai HM', drops:'Stygian creatures, Torment demons, Margonite Reapers (DoA has best density)', salvageItems:'Cannot be salvaged — drops only', kit:'N/A' }},
    { name:'Onyx Gemstone', front:{ use:'Vabbian elite armor (7 per piece)' }, back:{ areas:'Realm of Torment areas, Domain of Anguish, Nightfallen Jahai', drops:'Margonites, Torment creatures (same sources as Diamonds)', salvageItems:'Cannot be salvaged — drops only', kit:'N/A' }},
    { name:'Ruby', front:{ use:'Destroyer weapons, Vabbian armor' }, back:{ areas:'Destruction\'s Depths (EotN dungeon), Central Transfer Chamber', drops:'All Destroyer types. Dungeon end-chests also award them', salvageItems:'Cannot be salvaged — drops only', kit:'N/A' }},
    { name:'Sapphire', front:{ use:'Destroyer weapons, Norn elite armor' }, back:{ areas:'Destruction\'s Depths, Darkrime Delves (EotN ice dungeons)', drops:'Destroyers (especially ice variants), ice dungeon end-chests', salvageItems:'Cannot be salvaged — drops only', kit:'N/A' }},
    { name:'Deldrimor Steel Ingot', front:{ use:'Deldrimor armor, Destroyer weapons' }, back:{ areas:'Crafted at EotN artisans (recipe: 10 Iron Ingots + 1 Lump of Charcoal + 200g)', drops:'Not commonly dropped — crafted from farmed Iron Ingots (Vaettir farm)', salvageItems:'Rare chance from gold EotN Deldrimor-themed weapons', kit:'Superior Salvage Kit (rare)' }},
    { name:'Steel Ingot', front:{ use:'Elite heavy armor, weapon upgrades' }, back:{ areas:'Crafted at artisans (recipe: 10 Iron Ingots + 1 Lump of Charcoal + 200g). Southern Shiverpeaks HM for direct drops', drops:'Stone Summit Heretics (Southern Shiverpeaks HM), or craft from Iron + Charcoal', salvageItems:'Gold Dwarven weapons, gold metal hammers and axes', kit:'Expert or Superior Salvage Kit' }},
    { name:'Amber Chunk', front:{ use:'Kurzick elite armor, Amber weapons' }, back:{ areas:'Echovald Forest — any area. Or exchange 5,000 Kurzick faction at faction NPC', drops:'General Echovald Forest foe drops (Stone Scale Kirin, Wardens, Dredge)', salvageItems:'Gold Echovald/Kurzick weapons (Amber Longbow, etc.)', kit:'Expert or Superior Salvage Kit' }},
    { name:'Jadeite Shard', front:{ use:'Luxon elite armor, Jade weapons' }, back:{ areas:'Jade Sea — any area. Or exchange 5,000 Luxon faction at faction NPC', drops:'General Jade Sea foe drops (Leviathans, Outcasts, Naga)', salvageItems:'Gold Jade Sea/Luxon weapons (Jade Bow, Luxon Spear)', kit:'Expert or Superior Salvage Kit' }},
    { name:'Bolt of Linen', front:{ use:'Canthan and Elonian armor crafting' }, back:{ areas:'Kaineng City, Istan, Kourna — humanoid-heavy areas', drops:'Am Fah, Jade Brotherhood, Corsairs, Kournan soldiers', salvageItems:'Factions/Nightfall cloth salvage armor (robes, garments)', kit:'Any Salvage Kit' }},
    { name:'Bolt of Silk', front:{ use:'Elite Canthan armor (Kurzick/Luxon)' }, back:{ areas:'Echovald Forest endgame, Jade Sea endgame', drops:'Oni, Thought Stealers, Shiroken, elite Factions foes', salvageItems:'Gold Factions cloth armor drops', kit:'Expert or Superior Salvage Kit' }},
    { name:'Bolt of Damask', front:{ use:'Elite light armor (Nightfall, EotN)' }, back:{ areas:'Vabbi (Djinn areas), Domain of Anguish, Realm of Torment', drops:'Ruby Djinn, Sapphire Djinn, Margonites, Roaring Ethers', salvageItems:'Gold Nightfall cloth armor', kit:'Expert or Superior Salvage Kit' }},
    { name:'Leather Square', front:{ use:'Standard medium armor (all campaigns)' }, back:{ areas:'Any beast-heavy zone in Prophecies/Factions', drops:'Warthogs, Melandru\'s Stalkers, Lions, Minotaurs', salvageItems:'Blue/purple leather armor pieces (studded, tanned)', kit:'Any Salvage Kit' }},
    { name:'Elonian Leather Square', front:{ use:'Elonian elite medium armor' }, back:{ areas:'Kourna (centaurs), Vabbi (hekets), Desolation', drops:'Kournan beasts, Hekets, Rock-Borer Worms', salvageItems:'Gold Nightfall leather armor', kit:'Expert or Superior Salvage Kit' }},
    { name:'Fur Square', front:{ use:'Fur-lined Ranger armor, Norn armor (EotN)' }, back:{ areas:'Northern Shiverpeaks, Far Shiverpeaks, Norn territory', drops:'Black Bears, Polar Bears, Wolves, Snow Beasts', salvageItems:'Bear Pelt, Wolf Hide, fur-trimmed salvage items', kit:'Any Salvage Kit' }},
    { name:'Lump of Charcoal', front:{ use:'Steel/Deldrimor Steel ingredient' }, back:{ areas:'Ring of Fire (fire creatures), Sorrow\'s Furnace, EotN fire areas', drops:'Lava Spitters, Flame Djinn, Destroyers', salvageItems:'Fire-themed weapons (Fiery prefix)', kit:'Any Salvage Kit' }},
    { name:'Spiritwood Plank', front:{ use:'Elite staves, elite armor trim' }, back:{ areas:'Crafted (recipe: 10 Wood Planks + 1 Lump of Charcoal + 200g). Also spirit-type foes', drops:'Rare from spirit creatures; primarily crafted', salvageItems:'Gold staves/bows (rare chance)', kit:'Superior Salvage Kit (rare)' }},
    { name:'Roll of Parchment', front:{ use:'Focus item crafting, inscription blanks' }, back:{ areas:'Any caster-heavy area', drops:'Humanoid casters, especially monks and mesmers', salvageItems:'Scrolls, caster off-hand items (blue/purple)', kit:'Any Salvage Kit' }},
    { name:'Roll of Vellum', front:{ use:'Elite focus items, Powerstone of Courage' }, back:{ areas:'Crafted (recipe: 5 Rolls of Parchment + 200g at artisan)', drops:'Not commonly dropped — crafted from Rolls of Parchment', salvageItems:'Rare from gold focus items', kit:'Superior Salvage Kit (rare)' }},
    { name:'Tempered Glass Vial', front:{ use:'Focus item and wand crafting' }, back:{ areas:'Any area with caster enemies dropping wands/foci', drops:'Caster foes (monks, mesmers, elementalists)', salvageItems:'Wands, foci, jeweled items (blue/purple)', kit:'Any Salvage Kit' }},
    { name:'Vial of Ink', front:{ use:'Scroll crafting, inscription materials' }, back:{ areas:'Humanoid caster areas — Kaineng, Kryta, Vabbi', drops:'Caster humanoids (monks, mesmers, necromancers)', salvageItems:'Scrolls, purple/gold caster items', kit:'Any Salvage Kit' }},
    { name:'Monstrous Claw', front:{ use:'Weapon crafting, some elite armor' }, back:{ areas:'Kryta (griffons), Crystal Desert (giants), Desolation', drops:'Griffons, Ettins, Sand Giants, Siege Wurms', salvageItems:'Cannot be salvaged — drops only', kit:'N/A' }},
    { name:'Monstrous Eye', front:{ use:'Focus item and staff crafting' }, back:{ areas:'Ring of Fire (behemoths), Crystal Desert (hydras)', drops:'Behemoths, Hydras, Drakes, large monsters', salvageItems:'Cannot be salvaged — drops only', kit:'N/A' }},
    { name:'Monstrous Fang', front:{ use:'Weapon upgrades, some elite armor' }, back:{ areas:'Crystal Desert (hydras), Maguuma (wurms), Shiverpeaks', drops:'Hydras, Devourers, Jungle Wurms, Ice Drakes', salvageItems:'Cannot be salvaged — drops only', kit:'N/A' }},
  ],
  special: [
    { name:'Destroyer Core', front:{ use:'Destroyer weapon crafting (Seer\'s forge, EotN)' }, back:{ areas:'Central Transfer Chamber, Destruction\'s Depths, Slavers\' Exile (EotN dungeons)', drops:'All Destroyer types (Flesh, Bones, Hordes). End-chest bonus drops', salvageItems:'Cannot be salvaged — Destroyer drops only', kit:'N/A' }},
    { name:'Torment Gemstone', front:{ use:'Tormented weapons — prestige weapon skins' }, back:{ areas:'Domain of Anguish (4 zones: Ravenheart Gloom, City of Torc\'qua, Stygian Veil, Foundry of Failed Creations)', drops:'End-chest rewards from completing each DoA zone (1-3 per chest)', salvageItems:'Cannot be salvaged — DoA end-chest only', kit:'N/A' }},
    { name:'Armbraces of Truth', front:{ use:'Crafts ANY Tormented weapon — extremely valuable' }, back:{ areas:'Domain of Anguish — final boss encounter only', drops:'Mallyx the Unyielding (requires completing all 4 DoA zones first, then killing the final boss)', salvageItems:'Cannot be salvaged — Mallyx boss drop only (very rare)', kit:'N/A' }},
  ],
  salvageKits: [
    { name:'Salvage Kit', cost:'100g', charges:25, desc:'Basic — extracts common materials from white/blue items. Use on Vaettir farm drops for Iron Ingots.' },
    { name:'Expert Salvage Kit', cost:'400g', charges:25, desc:'Recovers upgrades (runes, insignias, mods). Extracts rare materials from purple/gold items.' },
    { name:'Superior Salvage Kit', cost:'2p', charges:100, desc:'Same as Expert, 100 charges. Best for bulk salvaging gold items.' },
    { name:'Perfect Salvage Kit', cost:'See details', charges:5, desc:'Guarantees mod recovery without destroying the item. Rare — save for expensive upgrades.', isPerfect: true,
      crafters: [
        { npc:'Edwin', location:'Eye of the North, Embark Beach', cost:'250g + 25 Wood Planks + 25 Iron Ingots + 1 Skill Point', title:'Sealth Agent' },
        { npc:'Stealth Agent Kwat', location:'Rata Sum, Embark Beach', cost:'250g + 25 Wood Planks + 25 Iron Ingots + 1 Skill Point', title:'Not Too Clumsy' },
        { npc:'Eyja', location:"Gunnar's Hold, Embark Beach", cost:'250g + 25 Wood Planks + 25 Iron Ingots + 1 Skill Point', title:'Slayer of Nightmares' },
        { npc:'Alcus Nailbiter', location:'Central Transfer Chamber, Embark Beach', cost:'250g + 25 Wood Planks + 25 Iron Ingots + 1 Skill Point', title:'Gutsy Delver' },
        { npc:'Pokhe', location:'Great Temple of Balthazar, Embark Beach', cost:'3 Silver Zaishen Coins + 50g', title:'None' },
      ]},
  ],
};


// ── Approximate material prices (community estimates, NOT official) ────
// These are rough ranges from GW Legacy/community trading posts circa 2024.
// Actual in-game prices fluctuate. Always check the material trader.
var MATERIAL_PRICES = {
  // Common materials (per unit)
  'Bone': '~50-80g', 'Bolt of Cloth': '~50-80g', 'Chitin Fragment': '~50-80g',
  'Feather': '~80-120g', 'Granite Slab': '~80-120g', 'Iron Ingot': '~100-150g',
  'Pile of Glittering Dust': '~80-120g', 'Plant Fiber': '~50-80g',
  'Scale': '~50-80g', 'Tanned Hide Square': '~50-80g', 'Wood Plank': '~80-120g',
  // Rare materials (per unit)
  'Glob of Ectoplasm': '~4-7p', 'Obsidian Shard': '~1-2p',
  'Diamond': '~800g-1.5p', 'Onyx Gemstone': '~800g-1.5p',
  'Ruby': '~500g-1p', 'Sapphire': '~500g-1p',
  'Steel Ingot': '~400-800g', 'Deldrimor Steel Ingot': '~1-2p',
  'Amber Chunk': '~500g-1p', 'Jadeite Shard': '~500g-1p',
  'Bolt of Damask': '~500g-1p', 'Bolt of Silk': '~300-600g',
  'Bolt of Linen': '~100-200g', 'Roll of Parchment': '~100-200g',
  'Roll of Vellum': '~400-800g', 'Tempered Glass Vial': '~100-200g',
  'Vial of Ink': '~100-200g', 'Spiritwood Plank': '~1-2p',
  'Monstrous Claw': '~100-200g', 'Monstrous Eye': '~100-200g',
  'Monstrous Fang': '~100-200g', 'Leather Square': '~200-400g',
  'Elonian Leather Square': '~400-800g', 'Fur Square': '~200-400g',
  'Leather Square': '~200-400g', 'Lump of Charcoal': '~100-200g',
  'Destroyer Core': '~1-3p', 'Torment Gemstone': '~9-15p',
  'Armbraces of Truth': '~100-250p',
};

// ── Armor crafting recipes (wiki-verified) ───────────────────
// Format: { name, ar, gold, materials: [{name, qty}], location }
// Sources: wiki.guildwars.com armor pages (crafting tables)
// Material amounts are approximate full-set totals (head×1 + chest×3 + arms×1 + legs×2 + feet×1 = 8 units)
var ARMOR_RECIPES = {
  1: [ // Warrior
    { name:'Ascalon (AR 35)', ar:35, gold:800, location:'Ascalon City (Banoit)',
      materials:[{name:'Iron Ingot',qty:8}]},
    { name:'Ascalon (AR 50)', ar:50, gold:3000, location:'Ascalon City (Corwen) / Yak\'s Bend',
      materials:[{name:'Iron Ingot',qty:16}]},
    { name:'Krytan (AR 59)', ar:59, gold:4000, location:'Bergen Hot Springs / Lion\'s Arch',
      materials:[{name:'Iron Ingot',qty:24}]},
    { name:'Tyrian Max (AR 80)', ar:80, gold:5000, location:"Droknar's Forge",
      materials:[{name:'Iron Ingot',qty:200},{name:'Tanned Hide Square',qty:32}]},
    { name:'Gladiator Max (AR 80)', ar:80, gold:5000, location:"Droknar's Forge",
      materials:[{name:'Iron Ingot',qty:175},{name:'Tanned Hide Square',qty:45},{name:'Bolt of Cloth',qty:15}]},
    { name:'Knight\'s Max (AR 80)', ar:80, gold:5000, location:"Droknar's Forge",
      materials:[{name:'Iron Ingot',qty:200},{name:'Steel Ingot',qty:16}]},
    { name:'Canthan Max (AR 80)', ar:80, gold:5000, location:'Kaineng Center',
      materials:[{name:'Iron Ingot',qty:200},{name:'Bolt of Linen',qty:32}]},
    { name:'Elonian Max (AR 80)', ar:80, gold:5000, location:'Consulate Docks',
      materials:[{name:'Iron Ingot',qty:160},{name:'Tanned Hide Square',qty:48},{name:'Granite Slab',qty:24}]},
    { name:'Vabbian Prestige (AR 80)', ar:80, gold:75000, location:'Vabbi armorers',
      materials:[{name:'Iron Ingot',qty:350},{name:'Diamond',qty:30},{name:'Onyx Gemstone',qty:35},{name:'Ruby',qty:15},{name:'Sapphire',qty:15}]},
    { name:'Obsidian / FoW (AR 80)', ar:80, gold:75000, location:'Fissure of Woe (Eternal Forgemaster)',
      materials:[{name:'Iron Ingot',qty:400},{name:'Obsidian Shard',qty:40},{name:'Glob of Ectoplasm',qty:120},{name:'Lump of Charcoal',qty:120}]},
  ],
  2: [ // Ranger
    { name:'Ascalon (AR 30)', ar:30, gold:800, location:'Ascalon City',
      materials:[{name:'Tanned Hide Square',qty:8}]},
    { name:'Ascalon (AR 42)', ar:42, gold:3000, location:'Ascalon City / Yak\'s Bend',
      materials:[{name:'Tanned Hide Square',qty:16}]},
    { name:'Krytan (AR 51)', ar:51, gold:4000, location:'Bergen Hot Springs / Lion\'s Arch',
      materials:[{name:'Tanned Hide Square',qty:24}]},
    { name:'Druidic Max (AR 70)', ar:70, gold:5000, location:"Droknar's Forge",
      materials:[{name:'Tanned Hide Square',qty:175},{name:'Plant Fiber',qty:45}]},
    { name:'Fur-Lined Max (AR 70)', ar:70, gold:5000, location:"Droknar's Forge",
      materials:[{name:'Tanned Hide Square',qty:150},{name:'Fur Square',qty:32}]},
    { name:'Canthan Max (AR 70)', ar:70, gold:5000, location:'Kaineng Center',
      materials:[{name:'Tanned Hide Square',qty:160},{name:'Bolt of Linen',qty:40},{name:'Scale',qty:24}]},
    { name:'Elonian Max (AR 70)', ar:70, gold:5000, location:'Consulate Docks',
      materials:[{name:'Tanned Hide Square',qty:160},{name:'Chitin Fragment',qty:40},{name:'Plant Fiber',qty:24}]},
    { name:'Vabbian Prestige (AR 70)', ar:70, gold:75000, location:'Vabbi armorers',
      materials:[{name:'Tanned Hide Square',qty:300},{name:'Diamond',qty:30},{name:'Onyx Gemstone',qty:35},{name:'Ruby',qty:15},{name:'Sapphire',qty:15}]},
    { name:'Obsidian / FoW (AR 70)', ar:70, gold:75000, location:'Fissure of Woe',
      materials:[{name:'Tanned Hide Square',qty:350},{name:'Obsidian Shard',qty:40},{name:'Glob of Ectoplasm',qty:120},{name:'Lump of Charcoal',qty:120}]},
  ],
  3: [ // Monk
    { name:'Ascalon (AR 20)', ar:20, gold:800, location:'Ascalon City',
      materials:[{name:'Bolt of Cloth',qty:8}]},
    { name:'Ascalon (AR 32)', ar:32, gold:3000, location:'Ascalon City / Yak\'s Bend',
      materials:[{name:'Bolt of Cloth',qty:16}]},
    { name:'Krytan (AR 42)', ar:42, gold:4000, location:'Bergen Hot Springs / Lion\'s Arch',
      materials:[{name:'Bolt of Cloth',qty:24}]},
    { name:'Ascetic Max (AR 60)', ar:60, gold:5000, location:"Droknar's Forge",
      materials:[{name:'Bolt of Cloth',qty:175},{name:'Pile of Glittering Dust',qty:40}]},
    { name:'Woven Max (AR 60)', ar:60, gold:5000, location:"Droknar's Forge",
      materials:[{name:'Bolt of Cloth',qty:150},{name:'Plant Fiber',qty:50}]},
    { name:'Canthan Max (AR 60)', ar:60, gold:5000, location:'Kaineng Center',
      materials:[{name:'Bolt of Cloth',qty:140},{name:'Bolt of Linen',qty:50},{name:'Pile of Glittering Dust',qty:24}]},
    { name:'Elonian Max (AR 60)', ar:60, gold:5000, location:'Consulate Docks',
      materials:[{name:'Bolt of Cloth',qty:140},{name:'Plant Fiber',qty:40},{name:'Feather',qty:32}]},
    { name:'Vabbian Prestige (AR 60)', ar:60, gold:75000, location:'Vabbi armorers',
      materials:[{name:'Bolt of Cloth',qty:300},{name:'Diamond',qty:30},{name:'Onyx Gemstone',qty:35},{name:'Ruby',qty:15},{name:'Sapphire',qty:15}]},
    { name:'Obsidian / FoW (AR 60)', ar:60, gold:75000, location:'Fissure of Woe',
      materials:[{name:'Bolt of Cloth',qty:350},{name:'Obsidian Shard',qty:40},{name:'Glob of Ectoplasm',qty:120},{name:'Lump of Charcoal',qty:120}]},
  ],
  4: [ // Necromancer
    { name:'Ascalon (AR 20)', ar:20, gold:800, location:'Ascalon City',
      materials:[{name:'Bolt of Cloth',qty:8}]},
    { name:'Ascalon (AR 32)', ar:32, gold:3000, location:'Ascalon City / Yak\'s Bend',
      materials:[{name:'Bolt of Cloth',qty:16}]},
    { name:'Krytan (AR 42)', ar:42, gold:4000, location:'Bergen Hot Springs / Lion\'s Arch',
      materials:[{name:'Bolt of Cloth',qty:24}]},
    { name:'Fanatic Max (AR 60)', ar:60, gold:5000, location:"Droknar's Forge",
      materials:[{name:'Bolt of Cloth',qty:150},{name:'Bone',qty:60}]},
    { name:'Scar Pattern Max (AR 60)', ar:60, gold:5000, location:"Droknar's Forge",
      materials:[{name:'Bolt of Cloth',qty:160},{name:'Tanned Hide Square',qty:40}]},
    { name:'Canthan Max (AR 60)', ar:60, gold:5000, location:'Kaineng Center',
      materials:[{name:'Bolt of Cloth',qty:140},{name:'Bolt of Linen',qty:50},{name:'Bone',qty:24}]},
    { name:'Elonian Max (AR 60)', ar:60, gold:5000, location:'Consulate Docks',
      materials:[{name:'Bolt of Cloth',qty:140},{name:'Bone',qty:50},{name:'Pile of Glittering Dust',qty:32}]},
    { name:'Vabbian Prestige (AR 60)', ar:60, gold:75000, location:'Vabbi armorers',
      materials:[{name:'Bolt of Cloth',qty:300},{name:'Diamond',qty:30},{name:'Onyx Gemstone',qty:35},{name:'Ruby',qty:15},{name:'Sapphire',qty:15}]},
    { name:'Obsidian / FoW (AR 60)', ar:60, gold:75000, location:'Fissure of Woe',
      materials:[{name:'Bolt of Cloth',qty:350},{name:'Obsidian Shard',qty:40},{name:'Glob of Ectoplasm',qty:120},{name:'Lump of Charcoal',qty:120}]},
  ],
  5: [ // Mesmer
    { name:'Ascalon (AR 20)', ar:20, gold:800, location:'Ascalon City',
      materials:[{name:'Bolt of Cloth',qty:8}]},
    { name:'Ascalon (AR 32)', ar:32, gold:3000, location:'Ascalon City / Yak\'s Bend',
      materials:[{name:'Bolt of Cloth',qty:16}]},
    { name:'Krytan (AR 42)', ar:42, gold:4000, location:'Bergen Hot Springs / Lion\'s Arch',
      materials:[{name:'Bolt of Cloth',qty:24}]},
    { name:'Enchanter Max (AR 60)', ar:60, gold:5000, location:"Droknar's Forge",
      materials:[{name:'Bolt of Cloth',qty:175},{name:'Pile of Glittering Dust',qty:40}]},
    { name:'Canthan Max (AR 60)', ar:60, gold:5000, location:'Kaineng Center',
      materials:[{name:'Bolt of Cloth',qty:140},{name:'Bolt of Linen',qty:50},{name:'Pile of Glittering Dust',qty:24}]},
    { name:'Elonian Max (AR 60)', ar:60, gold:5000, location:'Consulate Docks',
      materials:[{name:'Bolt of Cloth',qty:140},{name:'Pile of Glittering Dust',qty:48},{name:'Plant Fiber',qty:24}]},
    { name:'Vabbian Prestige (AR 60)', ar:60, gold:75000, location:'Vabbi armorers',
      materials:[{name:'Bolt of Cloth',qty:300},{name:'Diamond',qty:30},{name:'Onyx Gemstone',qty:35},{name:'Ruby',qty:15},{name:'Sapphire',qty:15}]},
    { name:'Obsidian / FoW (AR 60)', ar:60, gold:75000, location:'Fissure of Woe',
      materials:[{name:'Bolt of Cloth',qty:350},{name:'Obsidian Shard',qty:40},{name:'Glob of Ectoplasm',qty:120},{name:'Lump of Charcoal',qty:120}]},
  ],
  6: [ // Elementalist
    { name:'Ascalon (AR 20)', ar:20, gold:800, location:'Ascalon City',
      materials:[{name:'Bolt of Cloth',qty:8}]},
    { name:'Ascalon (AR 32)', ar:32, gold:3000, location:'Ascalon City / Yak\'s Bend',
      materials:[{name:'Bolt of Cloth',qty:16}]},
    { name:'Krytan (AR 42)', ar:42, gold:4000, location:'Bergen Hot Springs / Lion\'s Arch',
      materials:[{name:'Bolt of Cloth',qty:24}]},
    { name:'Stormforged Max (AR 60)', ar:60, gold:5000, location:"Droknar's Forge",
      materials:[{name:'Bolt of Cloth',qty:150},{name:'Granite Slab',qty:45}]},
    { name:'Canthan Max (AR 60)', ar:60, gold:5000, location:'Kaineng Center',
      materials:[{name:'Bolt of Cloth',qty:140},{name:'Bolt of Linen',qty:50},{name:'Granite Slab',qty:24}]},
    { name:'Elonian Max (AR 60)', ar:60, gold:5000, location:'Consulate Docks',
      materials:[{name:'Bolt of Cloth',qty:140},{name:'Granite Slab',qty:48},{name:'Iron Ingot',qty:24}]},
    { name:'Vabbian Prestige (AR 60)', ar:60, gold:75000, location:'Vabbi armorers',
      materials:[{name:'Bolt of Cloth',qty:300},{name:'Diamond',qty:30},{name:'Onyx Gemstone',qty:35},{name:'Ruby',qty:15},{name:'Sapphire',qty:15}]},
    { name:'Obsidian / FoW (AR 60)', ar:60, gold:75000, location:'Fissure of Woe',
      materials:[{name:'Bolt of Cloth',qty:350},{name:'Obsidian Shard',qty:40},{name:'Glob of Ectoplasm',qty:120},{name:'Lump of Charcoal',qty:120}]},
  ],
  7: [ // Assassin
    { name:'Shing Jea (AR 30)', ar:30, gold:800, location:'Shing Jea Monastery',
      materials:[{name:'Tanned Hide Square',qty:8}]},
    { name:'Shing Jea (AR 42)', ar:42, gold:3000, location:'Ran Musu Gardens',
      materials:[{name:'Tanned Hide Square',qty:16}]},
    { name:'Seitung (AR 57)', ar:57, gold:4000, location:'Seitung Harbor',
      materials:[{name:'Tanned Hide Square',qty:36},{name:'Bolt of Linen',qty:12}]},
    { name:'Canthan Max (AR 70)', ar:70, gold:5000, location:'Kaineng Center',
      materials:[{name:'Tanned Hide Square',qty:140},{name:'Bolt of Cloth',qty:50},{name:'Bolt of Linen',qty:30}]},
    { name:'Kurzick Max (AR 70)', ar:70, gold:5000, location:'Vasburg Armory (Kurzick)',
      materials:[{name:'Tanned Hide Square',qty:140},{name:'Amber Chunk',qty:16},{name:'Bolt of Silk',qty:20}]},
    { name:'Luxon Max (AR 70)', ar:70, gold:5000, location:'Leviathan Pits (Luxon)',
      materials:[{name:'Tanned Hide Square',qty:140},{name:'Jadeite Shard',qty:16},{name:'Bolt of Silk',qty:20}]},
    { name:'Vabbian Prestige (AR 70)', ar:70, gold:75000, location:'Vabbi armorers',
      materials:[{name:'Tanned Hide Square',qty:300},{name:'Diamond',qty:30},{name:'Onyx Gemstone',qty:35},{name:'Ruby',qty:15},{name:'Sapphire',qty:15}]},
    { name:'Obsidian / FoW (AR 70)', ar:70, gold:75000, location:'Fissure of Woe',
      materials:[{name:'Tanned Hide Square',qty:350},{name:'Obsidian Shard',qty:40},{name:'Glob of Ectoplasm',qty:120},{name:'Lump of Charcoal',qty:120}]},
  ],
  8: [ // Ritualist
    { name:'Shing Jea (AR 15)', ar:15, gold:800, location:'Shing Jea Monastery',
      materials:[{name:'Bolt of Cloth',qty:8}]},
    { name:'Shing Jea (AR 32)', ar:32, gold:3000, location:'Ran Musu Gardens',
      materials:[{name:'Bolt of Cloth',qty:16}]},
    { name:'Seitung (AR 48)', ar:48, gold:4000, location:'Seitung Harbor',
      materials:[{name:'Bolt of Cloth',qty:36},{name:'Bolt of Linen',qty:12}]},
    { name:'Canthan Max (AR 60)', ar:60, gold:5000, location:'Kaineng Center',
      materials:[{name:'Bolt of Cloth',qty:140},{name:'Bolt of Linen',qty:50},{name:'Pile of Glittering Dust',qty:30}]},
    { name:'Kurzick Max (AR 60)', ar:60, gold:5000, location:'Vasburg Armory (Kurzick)',
      materials:[{name:'Bolt of Cloth',qty:140},{name:'Amber Chunk',qty:16},{name:'Bolt of Silk',qty:20}]},
    { name:'Luxon Max (AR 60)', ar:60, gold:5000, location:'Leviathan Pits (Luxon)',
      materials:[{name:'Bolt of Cloth',qty:140},{name:'Jadeite Shard',qty:16},{name:'Bolt of Silk',qty:20}]},
    { name:'Vabbian Prestige (AR 60)', ar:60, gold:75000, location:'Vabbi armorers',
      materials:[{name:'Bolt of Cloth',qty:300},{name:'Diamond',qty:30},{name:'Onyx Gemstone',qty:35},{name:'Ruby',qty:15},{name:'Sapphire',qty:15}]},
    { name:'Obsidian / FoW (AR 60)', ar:60, gold:75000, location:'Fissure of Woe',
      materials:[{name:'Bolt of Cloth',qty:350},{name:'Obsidian Shard',qty:40},{name:'Glob of Ectoplasm',qty:120},{name:'Lump of Charcoal',qty:120}]},
  ],
  9: [ // Paragon
    { name:'Istani (AR 35)', ar:35, gold:800, location:'Kamadan / Sunspear Great Hall',
      materials:[{name:'Iron Ingot',qty:6},{name:'Bolt of Cloth',qty:4}]},
    { name:'Kournan (AR 55)', ar:55, gold:3000, location:'Camp Hojanu / Moddok Crevice',
      materials:[{name:'Iron Ingot',qty:12},{name:'Bolt of Cloth',qty:8}]},
    { name:'Elonian Max (AR 80)', ar:80, gold:5000, location:'Consulate Docks',
      materials:[{name:'Iron Ingot',qty:140},{name:'Tanned Hide Square',qty:60},{name:'Bolt of Cloth',qty:30}]},
    { name:'Sunspear Max (AR 80)', ar:80, gold:5000, location:'Sunspear Sanctuary',
      materials:[{name:'Iron Ingot',qty:160},{name:'Granite Slab',qty:40},{name:'Tanned Hide Square',qty:24}]},
    { name:'Vabbian Prestige (AR 80)', ar:80, gold:75000, location:'Vabbi armorers',
      materials:[{name:'Iron Ingot',qty:350},{name:'Diamond',qty:30},{name:'Onyx Gemstone',qty:35},{name:'Ruby',qty:15},{name:'Sapphire',qty:15}]},
    { name:'Obsidian / FoW (AR 80)', ar:80, gold:75000, location:'Fissure of Woe',
      materials:[{name:'Iron Ingot',qty:350},{name:'Obsidian Shard',qty:40},{name:'Glob of Ectoplasm',qty:120},{name:'Lump of Charcoal',qty:120}]},
  ],
  10: [ // Dervish
    { name:'Istani (AR 30)', ar:30, gold:800, location:'Kamadan / Sunspear Great Hall',
      materials:[{name:'Tanned Hide Square',qty:6},{name:'Bolt of Cloth',qty:4}]},
    { name:'Kournan (AR 48)', ar:48, gold:3000, location:'Camp Hojanu / Moddok Crevice',
      materials:[{name:'Tanned Hide Square',qty:12},{name:'Bolt of Cloth',qty:8}]},
    { name:'Elonian Max (AR 70)', ar:70, gold:5000, location:'Consulate Docks',
      materials:[{name:'Tanned Hide Square',qty:140},{name:'Bolt of Cloth',qty:60},{name:'Iron Ingot',qty:30}]},
    { name:'Sunspear Max (AR 70)', ar:70, gold:5000, location:'Sunspear Sanctuary',
      materials:[{name:'Tanned Hide Square',qty:160},{name:'Chitin Fragment',qty:40},{name:'Plant Fiber',qty:24}]},
    { name:'Vabbian Prestige (AR 70)', ar:70, gold:75000, location:'Vabbi armorers',
      materials:[{name:'Tanned Hide Square',qty:300},{name:'Diamond',qty:30},{name:'Onyx Gemstone',qty:35},{name:'Ruby',qty:15},{name:'Sapphire',qty:15}]},
    { name:'Obsidian / FoW (AR 70)', ar:70, gold:75000, location:'Fissure of Woe',
      materials:[{name:'Tanned Hide Square',qty:350},{name:'Obsidian Shard',qty:40},{name:'Glob of Ectoplasm',qty:120},{name:'Lump of Charcoal',qty:120}]},
  ],
};
