/* titles-data.js — Title track farming guide (community-verified sources) */
var TITLE_FARMS = [
  { title:'Sunspear', campaign:'Nightfall', campaignAbbr:'Nightfall', maxRank:'Spearmarshal (10)', difficulty:'Easy', gwamm:true,
    icon:'https://wiki.guildwars.com/wiki/Special:FilePath/Sunspear_rank.jpg',
    tiers:[
      {rank:1, name:'Sunspear Sergeant', pts:50, bonus:'Unlock Sunspear skills + 1 hero skill point (cumulative)'},
      {rank:2, name:'Sunspear Master Sergeant', pts:100, bonus:'+1 hero skill point (cumulative)'},
      {rank:3, name:'Second Spear', pts:175, bonus:'+2 hero skill points (cumulative)'},
      {rank:4, name:'First Spear', pts:300, bonus:'+2 hero skill points (cumulative) + 15 attribute points quest'},
      {rank:5, name:'Sunspear Captain', pts:500, bonus:'Sunspear skills reach max effectiveness + 2 hero skill points'},
      {rank:6, name:'Sunspear Commander', pts:'1,000', bonus:'+2 hero skill points (cumulative, skills already maxed)'},
      {rank:7, name:'Sunspear General', pts:'2,500', bonus:'+2 hero skill points (cumulative)'},
      {rank:8, name:'Sunspear Castellan', pts:'7,500', bonus:'+2 hero skill points (cumulative)'},
      {rank:9, name:'Spearmarshal', pts:'15,000', bonus:'+2 hero skill points (cumulative)'},
      {rank:10, name:'Legendary Spearmarshal', pts:'50,000', bonus:'+2 hero skill points (cumulative, title maxed)'},
    ],
    farms:[
    { method:'Cliffs of Dohjok Harpy Farm', rate:'~1,600-3,100 pts/hr', desc:'Take quests "Skree Hatchling Season" and "Diamond in the Rough" from Champion\'s Dawn. Get bounty from Sunspear Scout, kill ~50 harpies, map back, abandon quests, repeat. 3 min/run.' },
    { method:'Arkjok Ward Insect Farm', rate:'~1,600 pts/hr', desc:'From Yohlon Haven, take Insect Hunt bounty. Kill 5 nearby groups of insects (20 total). ~96 pts per 3-min run. Works with any team composition.' },
    { method:'Sulfurous Wastes (late game)', rate:'~2,000+ pts/hr', desc:'From Gate of Desolation, take bounty and clear undead. Higher point density but requires Desolation access.' },
    { method:'Vanquishing + Bounties', rate:'Passive', desc:'Vanquishing any Nightfall area with an active bounty gives large point totals. Maxes title naturally by Guardian of Elona completion.' },
  ]},
  { title:'Lightbringer', campaign:'Nightfall', campaignAbbr:'Nightfall', maxRank:'Holy Lightbringer (8)', difficulty:'Medium', gwamm:true,
    icon:'https://wiki.guildwars.com/wiki/Special:FilePath/Lightbringer_rank.jpg',
    tiers:[
      {rank:1, name:'Lightbringer', pts:100, bonus:'Unlock Lightbringer skills + 1 hero skill point (cumulative)'},
      {rank:2, name:'Adept Lightbringer', pts:300, bonus:'+1 hero skill point (cumulative)'},
      {rank:3, name:'Brave Lightbringer', pts:'1,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:4, name:'Mighty Lightbringer', pts:'2,500', bonus:'+1 hero skill point (cumulative)'},
      {rank:5, name:'Conquering Lightbringer', pts:'7,500', bonus:'+1 hero skill point (cumulative)'},
      {rank:6, name:'Vanquishing Lightbringer', pts:'15,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:7, name:'Revered Lightbringer', pts:'25,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:8, name:'Holy Lightbringer', pts:'50,000', bonus:'+1 hero skill point (cumulative, title maxed)'},
    ],
    farms:[
    { method:'Domain of Anguish Farming', rate:'~3,000+ pts/hr', desc:'Clearing any DoA zone with Lightbringer bounty active. Best points per kill but requires endgame access and strong team.' },
    { method:'Realm of Torment bounty runs', rate:'~1,500 pts/hr', desc:'Take Lightbringer bounties in Realm of Torment areas. Kill Margonites and Torment creatures with bounty active.' },
    { method:'Gate of Pain / Nightfallen Jahai', rate:'~1,200 pts/hr', desc:'Dense demon spawns with bounty active. More accessible than DoA.' },
    { method:'Vanquishing Realm of Torment', rate:'Passive', desc:'Vanquishing with bounty active gives massive point totals per completion.' },
  ]},
  { title:'Norn', campaign:'Eye of the North', campaignAbbr:'Eye of the North', maxRank:'Legendary Norn (10)', difficulty:'Medium', gwamm:true,
    icon:'https://wiki.guildwars.com/wiki/Special:FilePath/Norn_rank.jpg',
    tiers:[
      {rank:1, name:'Slayer of Imps', pts:'1,000', bonus:'Max HP set to +60 (while displayed) + hero skill point + Heart of the Norn'},
      {rank:2, name:'Slayer of Beasts', pts:'4,000', bonus:'Max HP set to +70 (replaces previous) + hero skill point'},
      {rank:3, name:'Slayer of Nightmares', pts:'8,000', bonus:'Max HP set to +80 + hero skill point + Eyja (consumables vendor)'},
      {rank:4, name:'Slayer of Giants', pts:'16,000', bonus:'Max HP set to +90 + hero skill point + Keti (weaponsmith)'},
      {rank:5, name:'Slayer of Wurms', pts:'26,000', bonus:'Max HP set to +100 + hero skill point + Radi (armor crafter)'},
      {rank:6, name:'Slayer of Demons', pts:'40,000', bonus:'Max HP stays at +100 + hero skill point'},
      {rank:7, name:'Slayer of Heroes', pts:'56,000', bonus:'Max HP stays at +100 + hero skill point'},
      {rank:8, name:'Slayer of Champions', pts:'80,000', bonus:'Max HP stays at +100 + hero skill point (NM rep cap)'},
      {rank:9, name:'Slayer of Hordes', pts:'110,000', bonus:'Max HP stays at +100 + hero skill point'},
      {rank:10, name:'Slayer of All', pts:'160,000', bonus:'Max HP stays at +100 + hero skill point (title maxed)'},
    ],
    farms:[
    { method:'Vaettir Farm (Jaga Moraine HM)', rate:'~120-150 pts/run (2-3 min)', desc:'Kill 60 Spectral Vaettirs in HM. Fastest Norn point farm. Also gives Glittering Dust, Mesmer tomes, gold items, and event drops. Requires Shadow Form or equivalent build.' },
    { method:'Bjora Marches Vanquish', rate:'~800-1,200 pts', desc:'Vanquishing with Norn Hunt bounties. Good points + contributes to Master of the North.' },
    { method:'Norn Fighting Tournament', rate:'~100 pts/win', desc:'Quick repeatable tournament in Gunnar\'s Hold. Easy wins give consistent small point gains.' },
  ]},
  { title:'Ebon Vanguard', campaign:'Eye of the North', campaignAbbr:'Eye of the North', maxRank:'Legendary Vanguard (10)', difficulty:'Medium', gwamm:true,
    icon:'https://wiki.guildwars.com/wiki/Special:FilePath/Ebon_Vanguard_rank.jpg',
    tiers:[
      {rank:1, name:'Volunteer\'s Bane', pts:'1,000', bonus:'Unlock EV skills + 1 hero skill point (cumulative)'},
      {rank:2, name:'Recruit\'s Bane', pts:'4,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:3, name:'Soldier\'s Bane', pts:'8,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:4, name:'Noble\'s Bane', pts:'16,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:5, name:'Knight\'s Bane', pts:'26,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:6, name:'Commander\'s Bane', pts:'40,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:7, name:'Avenger\'s Bane', pts:'56,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:8, name:'Champion\'s Bane', pts:'80,000', bonus:'+1 hero skill point (cumulative, NM rep cap)'},
      {rank:9, name:'Hero\'s Bane', pts:'110,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:10, name:'Legendary Bane', pts:'160,000', bonus:'+1 hero skill point (cumulative, title maxed)'},
    ],
    farms:[
    { method:'Sacnoth Valley VQ with bounty', rate:'~1,000+ pts', desc:'Dense Charr spawns. Take Vanguard bounty and vanquish for best point-to-time ratio.' },
    { method:'Dalada Uplands + Grothmar VQ', rate:'~800-1,000 pts', desc:'Charr-heavy areas with bounties. Contributes to Master of the North simultaneously.' },
    { method:'Repeating "Against the Charr"', rate:'~400 pts/run', desc:'Quick repeatable quest with dense Charr spawns near Longeye\'s Ledge.' },
  ]},
  { title:'Deldrimor', campaign:'Eye of the North', campaignAbbr:'Eye of the North', maxRank:'Legendary Delver (10)', difficulty:'Hard', gwamm:true,
    icon:'https://wiki.guildwars.com/wiki/Special:FilePath/Deldrimor_rank.jpg',
    tiers:[
      {rank:1, name:'Delver', pts:'1,000', bonus:'Unlock Deldrimor skills + 1 hero skill point (cumulative)'},
      {rank:2, name:'Dungeoneer', pts:'4,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:3, name:'Spelunker', pts:'8,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:4, name:'Cavern Dweller', pts:'16,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:5, name:'Underground Nomad', pts:'26,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:6, name:'Depth Explorer', pts:'40,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:7, name:'Darkness Vanquisher', pts:'56,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:8, name:'Deep Delver', pts:'80,000', bonus:'+1 hero skill point (cumulative, NM rep cap)'},
      {rank:9, name:'Master Delver', pts:'110,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:10, name:'Legendary Delver', pts:'160,000', bonus:'+1 hero skill point (cumulative, title maxed)'},
    ],
    farms:[
    { method:'Slavers\' Exile dungeon runs', rate:'~800-1,200 pts/run', desc:'Full dungeon clear with Deldrimor bounty. Long runs but highest point total per completion.' },
    { method:'Catacombs of Kathandrax', rate:'~600-800 pts/run', desc:'Shorter dungeon with good Deldrimor point rewards. Farmable with heroes.' },
    { method:'Secret Lair of the Snowmen (seasonal)', rate:'~500 pts/run', desc:'During Wintersday event. Short dungeon, easy clears, Deldrimor points.' },
    { method:'Vanquishing Depths areas + bounties', rate:'Passive', desc:'Any Depths area vanquish with bounty contributes heavily.' },
  ]},
  { title:'Asura', campaign:'Eye of the North', campaignAbbr:'Eye of the North', maxRank:'Legendary Genius (10)', difficulty:'Easy', gwamm:true,
    icon:'https://wiki.guildwars.com/wiki/Special:FilePath/Asura_rank.jpg',
    tiers:[
      {rank:1, name:'Not Too Clumsy', pts:'1,000', bonus:'Unlock Asuran skills + 1 hero skill point (cumulative)'},
      {rank:2, name:'Almost Useful', pts:'4,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:3, name:'Barely Adequate', pts:'8,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:4, name:'Above Average', pts:'16,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:5, name:'Fairly Intelligent', pts:'26,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:6, name:'Clever', pts:'40,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:7, name:'Quite Brilliant', pts:'56,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:8, name:'Genius', pts:'80,000', bonus:'+1 hero skill point (cumulative, NM rep cap)'},
      {rank:9, name:'Grand Genius', pts:'110,000', bonus:'+1 hero skill point (cumulative)'},
      {rank:10, name:'Legendary Genius', pts:'160,000', bonus:'+1 hero skill point (cumulative, title maxed)'},
    ],
    farms:[
    { method:'Raptor Farm (Riven Earth)', rate:'~150-200 pts/run (3 min)', desc:'From Rata Sum, enter Riven Earth. Kill Raptors with AoE builds (they ball up). Fast runs, good Asuran points + gold items. Very popular farm.' },
    { method:'Polymock (repeatable)', rate:'~100 pts/win', desc:'Polymock wins in Rata Sum give Asuran points. Easy early source.' },
    { method:'Tarnished Coast VQs + bounty', rate:'~600-800 pts', desc:'Vanquish Tarnished Coast areas with Asuran bounty active.' },
  ]},
  { title:'Kurzick', campaign:'Factions', campaignAbbr:'Factions', maxRank:'Savior of the Kurzicks (12)', difficulty:'Medium', gwamm:true,
    icon:'https://wiki.guildwars.com/wiki/Special:FilePath/Kurzick_faction.png', farms:[
    { method:'Lutgardis FFF (Securing Echovald Forest)', rate:'~10,000-12,000 faction/hr', desc:'Repeat the quest "Securing Echovald Forest" from Lutgardis Conservatory. 400 faction per run, 1.5-2 min per run with optimized team. Fastest known Kurzick farm.' },
    { method:'Fort Aspenwood (PvP)', rate:'~5,000-8,000 faction/hr', desc:'Competitive mission. Win or lose you get faction. Wins give significantly more.' },
    { method:'Echovald Forest VQs + blessing', rate:'Passive', desc:'Vanquish with Blessing of the Kurzicks active for bonus faction per kill.' },
  ]},
  { title:'Luxon', campaign:'Factions', campaignAbbr:'Factions', maxRank:'Savior of the Luxons (12)', difficulty:'Medium', gwamm:true,
    icon:'https://wiki.guildwars.com/wiki/Special:FilePath/Luxon_faction.png', farms:[
    { method:'MQSC (Mount Qinkai Speed Clear)', rate:'~12,000+ faction/hr', desc:'Fastest Luxon faction farm. Requires prepared 8-man team with specific builds. Repeat Mount Qinkai mission rapidly.' },
    { method:'Jade Arena FFF', rate:'~8,000 faction/hr', desc:'Repeat The Jade Arena quest. 3-4 min per run. More accessible than MQSC.' },
    { method:'The Jade Quarry (PvP)', rate:'~5,000-8,000 faction/hr', desc:'Competitive mission. Win or lose gives faction. Popular for passive farming.' },
  ]},
  { title:'Wisdom', campaign:'Core', campaignAbbr:'Prophecies', maxRank:'Wise (varies)', difficulty:'Easy', gwamm:true,
    icon:'https://wiki.guildwars.com/wiki/Special:FilePath/Wisdom_title.jpg', farms:[
    { method:'Vaettir Farm + ID gold items', rate:'Passive', desc:'Vaettir farm drops many gold items. ID all of them for Wisdom points. Best combined with Norn title farming.' },
    { method:'Any endgame farm with gold drops', rate:'Passive', desc:'ID every gold item you find. Each ID = 1 point. Stacks naturally over time.' },
  ]},
  { title:'Treasure Hunter', campaign:'Core', campaignAbbr:'Prophecies', maxRank:'Treasure Hunter (varies)', difficulty:'Hard', gwamm:true,
    icon:'https://wiki.guildwars.com/wiki/Special:FilePath/Treasure_Hunter_title.jpg', farms:[
    { method:'Chest runs (Vabbi, FoW, UW)', rate:'Varies', desc:'Open locked chests with lockpicks. Each open = 1 point. Vabbi chest runs popular for density.' },
    { method:'Lockpick retention at high rank', rate:'Passive', desc:'Higher rank = higher chance lockpick isn\'t consumed. Becomes self-sustaining at high ranks.' },
  ]},
  { title:'Survivor', campaign:'Core', campaignAbbr:'Prophecies', maxRank:'Legendary Survivor (3)', difficulty:'Hard', gwamm:true,
    icon:'https://wiki.guildwars.com/wiki/Special:FilePath/Survivor_title.jpg', farms:[
    { method:'Vaettir Farm (never die)', rate:'~16,800 XP/run', desc:'280 XP per Vaettir × 60 = 16,800 per run. One of the fastest XP sources in game. Must never die on this character.' },
    { method:'Kilroy Stonekin punchout (EotN)', rate:'~10,000 XP/run', desc:'Repeatable quest with safe XP. Cannot die — use cautious builds.' },
    { method:'Scrolls + Hard Mode missions', rate:'High', desc:'Use XP scrolls during HM missions for multiplied XP. Stay safe, don\'t die.' },
  ]},
  { title:'Drunkard', campaign:'Core', campaignAbbr:'Prophecies', maxRank:'Incorrigible Ale-Hound (3)', difficulty:'Easy', gwamm:true,
    icon:'https://wiki.guildwars.com/wiki/Special:FilePath/Drunkard_title.jpg', farms:[
    { method:'Cheapest: Rice Wine + AFK', rate:'~1 min/point', desc:'Buy Rice Wine (cheap). Drink 1, wait until effect wears off, drink another. 10,000 minutes total. Many players AFK this in town.' },
    { method:'Event alcohol (holidays)', rate:'Varies', desc:'Holiday events drop alcohol. Stock up during events for free drunkard points.' },
  ]},
  { title:'Sweet Tooth', campaign:'Core', campaignAbbr:'Prophecies', maxRank:'Connoisseur of Confections (3)', difficulty:'Easy', gwamm:true,
    icon:'https://wiki.guildwars.com/wiki/Special:FilePath/Sweet_Tooth_title.jpg', farms:[
    { method:'Buy cheap sweets from events', rate:'Varies', desc:'Stock up on Birthday Cupcakes, Candy Corn, Candy Apples during events. Cheapest source.' },
    { method:'Nicholas the Traveler gifts', rate:'Weekly', desc:'Nick gifts contain random sweets. Free weekly source.' },
  ]},
  { title:'Party Animal', campaign:'Core', campaignAbbr:'Prophecies', maxRank:'Life of the Party (3)', difficulty:'Easy', gwamm:true,
    icon:'https://wiki.guildwars.com/wiki/Special:FilePath/Party_Animal_title.jpg', farms:[
    { method:'Cheapest: Sparklers + AFK', rate:'~1 min/point', desc:'Buy Sparklers (cheap party items). Use 1, wait, repeat. 10,000 uses total.' },
    { method:'Event party items', rate:'Varies', desc:'Holiday events give free party items. Stock up.' },
  ]},
];


// ── Weekly Bonus Rotation (wiki-verified, 9-week PvE cycle) ──────
// Changes every Monday at 15:00 UTC. Source: wiki.guildwars.com/wiki/Weekly_bonuses
var WEEKLY_BONUS_ROTATION = [
  { week:1, name:'Extra Luck Bonus', effect:'Keys and lockpicks drop at 4× rate. Double Lucky/Unlucky title points.', titles:['Lucky','Unlucky','Treasure Hunter'] },
  { week:2, name:'Elonian Support Bonus', effect:'Double Sunspear and Lightbringer reputation points.', titles:['Sunspear','Lightbringer'] },
  { week:3, name:'Zaishen Bounty Bonus', effect:'Double copper Zaishen Coin rewards for Zaishen bounties.', titles:['Zaishen'] },
  { week:4, name:'Factions Elite Bonus', effect:'The Deep and Urgoz\'s Warren can be entered from Kaineng Center.', titles:[] },
  { week:5, name:'Northern Support Bonus', effect:'Double Asura, Deldrimor, Ebon Vanguard, and Norn reputation points.', titles:['Asura','Deldrimor','Ebon Vanguard','Norn'] },
  { week:6, name:'Zaishen Mission Bonus', effect:'Double copper Zaishen Coin rewards for Zaishen missions.', titles:['Zaishen'] },
  { week:7, name:'Pantheon Bonus', effect:'Free passage to the Underworld and Fissure of Woe.', titles:['Treasure Hunter'] },
  { week:8, name:'Faction Support Bonus', effect:'Double Kurzick and Luxon title track points for exchanging faction.', titles:['Kurzick','Luxon'] },
  { week:9, name:'Zaishen Vanquishing Bonus', effect:'Double copper Zaishen Coin rewards for Zaishen vanquishes.', titles:['Zaishen'] },
];
